feat(util): add try_nonroot_first

diff --git a/utils b/utils
--- a/utils
+++ b/utils
@@ -10,10 +10,25 @@ as_root() {
   user="$(whoami)"
 
   if [ "$user" != 'root' ]; then
-    shell_cmd='sudo -E bash -c'
+    # shell_cmd='sudo -E bash -c'
+    if command_exists sudo; then
+      shell_cmd='sudo -E bash -c'
+    elif command_exists su; then
+      shell_cmd='su -c'
+    else
+      echo "[ERROR] Needs root. No sudo or su found"
+      exit 1
+    fi
   fi
   printf -v cmd_str "%q " "${cmd[@]}"
   $shell_cmd "$cmd_str"
+}
+
+try_nonroot_first() {
+  local cmd
+  cmd=("$@")
+  printf -v cmd_str '%q ' "${cmd[@]}"
+  bash -c "$cmd_str" || as_root "$cmd_str"
 }
 
 # Test whether a command exists
